### ISSUE TITLE
[bug]没有 /lib/index.js 文件

### ISSUE THREAD

**Issue by jrainlau** [ma125120/cjs2esmodule#1]
1.1.0 版本，通过 yarn 安装的。

```
Error: Cannot find module '/Users/xxx/Desktop/vite-demo/node_modules/cjs2esmodule/lib/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/liujun/Desktop/vite-demo/vite.config.js:31:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.require.extensions.<computed> [as .js] (/Users/liujun/Desktop/vite-demo/node_modules/vite/dist/node/chunks/dep-efe32886.js:46235:20)
    at Module.load (internal/modules/cjs/loader.js:928:32)
error Command failed with exit code 1.
```

是不是构建发布 npm 的时候出错了？

**Comment by ma125120** [comment]
.gitignore给忽略了，刚发了1.1.1版本，可以再试一下

**Comment by jrainlau** [comment]
> .gitignore给忽略了，刚发了1.1.1版本，可以再试一下

感谢！

**Comment by ma125120** [comment]
如果还有什么功能性建议的话都可以提，这个我就先关闭了
